# Site Settings
baseurl: ""
url : "https://leenakim.github.io"

# Blog Settings
theme_settings :
  title : Leena Kim
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/portfolio.jpeg
    username : Leena Kim
    description : Software developer
    experience :
      - start : 2021-01-08
        end :
        experience : Software Developer in finance, Republic of Korea
      - start : 2019-03-01
        end : 2019-09-01
        experience : Visiting Intern Researcher, United States
    skills :
      - skill : JAVA
        value : 80  # Percent value
      - skill : JSP & JAVASCRIPT
        value : 85  # Percent value
      - skill : PYTHON
        value : 70  # Percent value

  # Icons
  icons :
    email:  tmxkvk94@gmail.com
    linkedin:  https://www.linkedin.com/in/leena-kim-1bba9915a/
    github: LeenaKim
    gitlab:
    bitbucket:
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
plugins :
  - jemoji
